name: dagger-nscloud
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  packages: read
  contents: read
  id-token: write # This is required for requesting the JWT

jobs:
  build-nscloud:
    name: build-nscloud
    runs-on: nscloud
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - uses: actions/checkout@v3

      - uses: namespacelabs/nscloud-setup@v0
        id: nsc

      - name: Run Dagger pipeline
        run: go run ci/main.go -registry ${{ steps.nsc.outputs.registry-address }} -commit ${{ github.sha }}